### ISSUE TITLE
O método deveria retornar a cotação da ação (um valor double)

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/adapter-cotacao#2]
Sem isso, não tem como usar o método em outras apps que não sejam console.
Como poderia exibir o valor da cotação em uma app web se o método não retornar o valor para eu poder exibir em uma página?

https://github.com/trasherdave/adapter-cotacao/blob/5f095b6f47aac3fb13028f385f997e9a8f94cb0f/src/main/java/AdapterServicoCotacao.java#L13

**Comment by trasherdave** [comment]
Entendido!

**Comment by manoelcampos** [comment]
vc fechou a issue mas não resolveu o problema em AdapterServicoCotacao

**Comment by manoelcampos** [comment]
Vc alterou só as classes que implementam a interface que mencionei, mas não alterou a interface de fato.
Isto nem compila, pois a assinatura dos métodos nas classes vão ser diferentes do contrato definido na interface.

**Comment by trasherdave** [comment]
professor, eu alterei no meu projeto local e não subi a classe alterada, perdão! vou fazer o commit
